HRNET_MODEL:
  ALIGN_CORNERS: true
  PRETRAINED: "/mnt/ssd1/Pytorch_models/hrnetv2_w18_imagenet_pretrained.pth"
  CONFIGURATION:
    STEM_STRIDE: 4
    STEM_INPUT_CHANNEL: 3
    STEM_OUTPUT_CHANNEL: 64
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
        - 4
      NUM_CHANNELS:
        - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
        - 72
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 18
        - 36
        - 72
        - 144
      FUSE_METHOD: SUM
  PYRAMID_CHANNELS:
    - 64
    - 256
    - 256
    - 512
    - 512
OCRNET_MODEL:
  RAW_IN_CHANNELS: 270
  NUM_CLASSES: 17
  PIXEL_REP_CHANNELS: 512
  KEY_CHANNELS: 256




    
